### ISSUE TITLE
GoURL is hardcoded in link

### ISSUE THREAD

**Issue by FattusMannus** [LateRoomsGroup/GoDashboard#1]
In the href link of the pipeline on the page that lists all the profiles, there is a hard-coded value to the laterooms go server:

`Line 4 of _pipelines.spark:
`http://go.laterooms.com:8153/go/tab/pipeline/history/${pipeline.Name}

I would fix this and do a PR, but im not sure how spark works - sorry!

**Comment by paulclarkin** [comment]
Thanks for the comment, I'll update it with a config driven value!
