### ISSUE TITLE
Build issue? spark.web.mvc dependency

### ISSUE THREAD

**Issue by christrotter** [LateRoomsGroup/GoDashboard#2]
From what I can tell (I am not a developer, so maybe this is a total newbie mistake), spark.web.mvc doesn't have a version 1.6.0.0.  I get the following when trying to build:
![image](https://cloud.githubusercontent.com/assets/8292406/6596987/776338d8-c7cf-11e4-8360-a71ceae360d1.png)
 I've tried building in both VS2010 and VS2013.

If I try to install spark.web.mvc from NuGet directly, search is blank - there are, however spark.web.mvc2 and .mvc3.  Trying to install spark.web.mvc3 into this solution gives the error 'Could not install package WebActivator 1.4.1' due to .net framework targeting.

![image](https://cloud.githubusercontent.com/assets/8292406/6597018/c95f082e-c7cf-11e4-8694-21dd38220f01.png)

![image](https://cloud.githubusercontent.com/assets/8292406/6597025/d7016d5a-c7cf-11e4-936b-f4961f3a6848.png)

Suggestions?

**Comment by paulclarkin** [comment]
Oh no! I know whats happened here! Spark isn't on nuget.org, and is infact quite old. At some point someone has taken a version of Spark and packaged it up and put it on our own internal nuget server.  

To be honest, I hate Spark and its very out-dated now. This whole app needs reworking to latest .NET and use Razor instead.

For now, grab this zip file http://speedy.sh/H5DGA/Spark.Web.Mvc.1.6.0.0.zip and unzip it to your Packages folder. That should get you moving.

I'll start working on a rewrite/refactor ASAP!

**Comment by christrotter** [comment]
Wow - that was a prompt reply!  Thank you!  It built successfully after doing that - will let you know if anything else comes up.

I'm happy to help you with testing on this - we've settled on Go as our build/deploy automation platform at this point.

**Comment by paulclarkin** [comment]
Great, thanks. I'm considering rewriting it into something like node.js, but that will take a bit of time!

**Comment by paulclarkin** [comment]
I've updated the project, it now uses .NET 4.5, MVC 4 and uses Razor view engine instead of the ageing Spark. Let me know if you have any issues.

**Comment by christrotter** [comment]
![image](https://cloud.githubusercontent.com/assets/8292406/6639763/ab24e500-c968-11e4-81c7-15653b7cc028.png)
Played around with the old version and got this...will try out the new version next week!  You are awesome for resolving this so quickly.
