### ISSUE TITLE
Question: How to build via cli?

### ISSUE THREAD

**Issue by christrotter** [LateRoomsGroup/GoDashboard#4]
So I, as not a developer, have figured out a way to make this build via command line msbuild (and put it into Go!).  But I figured it couldn't hurt to ask how you guys are doing this - I am probably doing it wrong.

If this is the right way, then feel free to include the .proj file.  If it's totally wrong, I'd appreciate it if you could correct me/point me in the right direction!

My process:
1.Go gets TFS material (/GoDashboard)
2.msbuild.exe #{projectName}.proj /p:Configuration=Release /t:Release (working directory is GoDashboard.Web)
3.take the output files and send to webserver via scripts

Here's the .proj file I cobbled together (thanks to many internet msbuild tutorials):
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<MyReleaseOutput>.\output\$(MSBuildProjectName)</MyReleaseOutput>
		<Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
	</PropertyGroup>

	<Target Name="Build">
		<Message Text="Running the Build phase for: $(MSBuildProjectName) " />
		<MSBuild Projects="$(MSBuildProjectName).csproj" Targets="Build" />
	</Target>

	<Target Name="Release" DependsOnTargets="Build">
		<Message Text="Running the Release phase for: $(MSBuildProjectName) " />
		
		<MakeDir Directories="$(MyReleaseOutput)" />
		
		<ItemGroup>
			<MyReleaseFiles 
				Include="$(SourceRoot)**\*.*" 
				Exclude="$(SourceRoot)**\*.cs;$(SourceRoot)**\*.proj;$(SourceRoot)**\*.*proj" 
			/>
		</ItemGroup>

		<Copy 
			SourceFiles="@(MyReleaseFiles)" 
			DestinationFolder="$(MyReleaseOutput)\%(RecursiveDir)"
			SkipUnchangedFiles="false"
		/>
		<Message Text="   " />
		<Message Importance="high" Text="$(MSBuildProjectName) has built successfully!" />
		<Message Text="   " />
	</Target>
</Project>
```

As an addendum - our shop has ~30 developers, but nobody seems to know how to do anything other than VS2010 setup projects.  We're moving into VS2013 (no 'official' setup projects), so this whole 'use msbuild' thing is becoming a pertinent issue.

edit:  Pretty sure this method is missing out on those tests you have in there...I run into issues building the solution rather than the GoDashboard.Web.csproj file via this .proj build file.

**Comment by paulclarkin** [comment]
Thanks. In house we use Rake to call msbuild on the solution. This hasn't been open sourced as its so specific to what we do internally.

You should just be able to call msbuild and it build, without any extra changes. We run

"C:/Windows/Microsoft.NET/Framework64/v4.0.30319/MSBuild.exe" "GoDashboard.sln" "/verbosity:quiet" /p:configuration="release" /p:platform="Any CPU" "/target:Rebuild" /m /nologo /clp:ErrorsOnly /clp:WarningsOnly

This should generate a build into a "Staging" folder which should then be able to be copy & pasted, or xcopied somewhere. For other products we use MSDeploy (aka WebDeploy) but this project hasn't been configured for that.

Hope this helps.

**Comment by christrotter** [comment]
Thanks, Paul!  Will give that a shot.  Took a look at Rake - appears to be doing something similar (but probably way more extensible/easier?) to the .proj file...?

http://yuserinterface.com/dev/2013/01/05/rake-the-only-sensible-way-to-build-on-windows/

Do you have any suggestions for a .NET shop looking to move away from VS2010 setup projects?  Today we are only experimenting with msbuild - never been used until now.
