### ISSUE TITLE
Sorting by pipeline activity?

### ISSUE THREAD

**Issue by christrotter** [LateRoomsGroup/GoDashboard#5]
Hey, any suggestions on how you'd have the pipelines displayed not by alpha name, but by 'latest activity goes to the top'?

Right now we have too many pipelines to display comfortably on a single page.

Our alternate solution to this problem is to have a slideshow using the XML profiles, but that's a bit more manual (requires adding pipelines manually to new profiles).

**Comment by paulclarkin** [comment]
There's no feature for this at the minute, but you could add

```.OrderByDescending(x => x.LastBuildTime)``` to ```GoDashboard.Web\Views\Home\Groups.cshtml```

I might add this as a feature in future.

**Comment by christrotter** [comment]
Nice!!  Most excellent, thank you so much!
``` dotnet
@if (!Model.Groups.Any())
{
    foreach (var displayablePipeline in Model.Pipelines.OrderByDescending(x => x.LastBuildTime))
    {
        Html.RenderPartial("Pipeline", displayablePipeline);
    }
}
```
